name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: bahmutov/npm-install@v1
      - run: npm run build-keycloak-theme

  create_release:
    name: Create GitHub Release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: bahmutov/npm-install@v1
      
      # Build the Keycloak theme
      - name: Build Keycloak Theme
        run: npm run build-keycloak-theme
      
      # Get current date for release name
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_OUTPUT
      
      # Create release with the timestamped JAR
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.date.outputs.date }}
          tag_name: release-${{ steps.date.outputs.date }}
          target_commitish: main
          generate_release_notes: true
          draft: false
          files: dist_keycloak/keycloakify-theme-*.jar
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
