name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: bahmutov/npm-install@v1
      - run: npm run build-keycloak-theme
      
      # Only for PRs - we just want to verify the build works
      - if: github.event_name == 'pull_request'
        name: Build verification complete
        run: echo "Build verification successful"
      
      # For main branch pushes - Create the release
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_OUTPUT
      
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.date.outputs.date }}
          tag_name: release-${{ steps.date.outputs.date }}
          target_commitish: main
          generate_release_notes: true
          draft: false
          files: dist_keycloak/keycloakify-theme-*.jar
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
